### ISSUE TITLE
Add installation instructions (README, etc.)

### ISSUE THREAD

**Issue by henry-hz** [yamadapc/dotfiles#1]

**Comment by yamadapc** [comment]
I'm not super eager to do this. These are personal configuration files. Any questions or problems can be dealt with on a case by case basis.

**Comment by henry-hz** [comment]
@yamadapc  sorry for the delay, I am still getting used to github notifications, and I lost your answers.
in fact, I installed debian on my macbook pro and solved the problem :+1: 
many thanks for the dotfiles
